### ISSUE TITLE
pYAF halts

### ISSUE THREAD

**Issue by sada-narayanappa** [siwells/PyAF#1]
I tried to run the example snippet ...
pyAF seems to halt - I could never get past this error: Does this framework work?
It sits at this message
ave the 
             INFO:pyaf.std:START_TRAINING 'Ozone'
 <class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 3 columns):
Month    216 non-null object
Ozone    216 non-null float64
Date     216 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 5.1+ KB

Example from the document (YES - this is just an example ...I have the other variable such as "lExogenousData" correctly initialized)

import pyaf.ForecastEngine as autof
lEngine = autof.cForecastEngine()

csvfile_link = "https://raw.githubusercontent.com/antoinecarme/TimeSeriesData/master/ozone-la.csv"
ozone_dataframe = pd.read_csv(csvfile_link);
ozone_dataframe['Date'] = ozone_dataframe['Month'].apply(lambda x : datetime.datetime.strptime(x, "%Y-%m"))

ozone_dataframe.info()
lExogenousData = (exog_dataframe , ['Exog2' , 'Exog3' , 'Exog4',  'Exog5']) 
lEngine.train(ozone_dataframe , 'Date' , 'Ozone', 12 , lExogenousData);

**Comment by siwells** [comment]
I think you have the wrong project. This is the Pyaf project that you are loking for: https://github.com/antoinecarme/pyaf
